# Generated by Django 5.0.4 on 2024-04-10 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatepass',
            fields=[
                ('GatePassNo', models.AutoField(primary_key=True, serialize=False)),
                ('outdate', models.DateField()),
                ('indate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=100)),
                ('RegisterationNumber', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=100)),
                ('Residence', models.CharField(max_length=100)),
                ('insidehostel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hostelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostelBlock', models.CharField(max_length=100)),
                ('RoomNo', models.CharField(max_length=4)),
                ('Residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='DayScholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusFacility', models.BooleanField(default=False)),
                ('Address', models.CharField(max_length=100)),
                ('Residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
