# Generated by Django 5.0.4 on 2024-04-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
